# Generated by Django 5.2.9 on 2025-12-07 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clarity_score', models.IntegerField()),
                ('depth_score', models.IntegerField()),
                ('structure_score', models.IntegerField()),
                ('originality_score', models.IntegerField()),
                ('overall_score', models.IntegerField()),
                ('strengths', models.TextField()),
                ('improvements', models.TextField()),
                ('specific_suggestions', models.TextField()),
                ('raw_json', models.JSONField()),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sub_part.submission')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(default='free', max_length=20)),
                ('writing_level', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('role', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
