# Generated by Django 5.2.9 on 2025-12-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('challenge_type', models.CharField(choices=[('creative', 'Creative'), ('opinion', 'Opinion'), ('reflective', 'Reflective'), ('narrative', 'Narrative')], max_length=20)),
                ('days', models.IntegerField(default=7)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
