# Generated by Django 5.2.9 on 2025-12-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0003_remove_userprofile_plan_remove_userprofile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tone_preference',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='writing_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='referral_info',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
