# Generated by Django 5.2.9 on 2025-12-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0004_userprofile_tone_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='topic',
            field=models.CharField(max_length=300),
        ),
    ]
